#---------------------------------------------------------------------
#  GitHub Action Basics
#---------------------------------------------------------------------
name: My-GitHubActions-Basics
env:
  MY_APP_NAME: "MyApp"
  MY_PACKAGE_NAME: "MyApp-version-${{ github.sha }}"
on: 
  push:
    branches: 
      - master
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "hello world from job-1"
      - name: Multiline command
        run: |
          touch 1.txt
          ls -la
          echo "My application name is : ${{ MY_APP_NAME }}"
      - name: sleep
        run: sleep 3

  job-2:
    runs-on: ubuntu-latest
    needs: [job-1]
    steps:
      - name: print hello
        run: echo "hello world from job-2"
      - name: Print Name
        run: echo "My package name is : ${{ env.MY_PACKAGE_NAME }}"
      - name: sleep
        run: sleep 3
