#---------------------------------------------------------------------
#  GitHub Action Basics
#---------------------------------------------------------------------
name: My-GitHubActions-Basics
on: 
  push:
    branches: 
      - master
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "hello world from job-1"
      - name: Multiline command
        run: |
          touch 1.txt
          ls -la
      - name: sleep
        run: sleep 3

  job-2:
    runs-on: ubuntu-latest
    needs: [job-1]
    steps:
      - name: print hello
        run: echo "hello world from job-2"
      - name: run Ls-La
        run: ls -la
      - name: sleep
        run: sleep 3
