#---------------------------------------------------------------------
#  GitHub Action Basics
#  
#---------------------------------------------------------------------
name: My-GitHubActions-Basics
on: 
  push:
    branches: 
      - master
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:

      - name: print hello
        run: echo "hello world from job-1"

      - name: sleep
        run: sleep 3

  job-2:
    runs-on: ubuntu-latest
    steps:

      - name: print hello
        run: echo "hello world from job-2"

      - name: sleep
        run: sleep 3
