#---------------------------------------------------------------------
#  GitHub Action Basics
#---------------------------------------------------------------------
name: My-GitHubActions-Basics
env:
  MY_APP_NAME: "MyApp"
  MY_PACKAGE_NAME: "MyApp-version-${{ github.sha }}"
on: 
  push:
    branches: 
      - master
jobs:
  job-1:
    
    runs-on: ubuntu-latest
    steps:
    
      - name: print hello
        run: echo "hello world from job-1"
        
      - name: Multiline command
        run: |
          touch 1.txt
          ls -la
          echo "My application name is :${{ env.MY_APP_NAME }}"
          
      - name: sleep
        run: sleep 3

  job-2:
    runs-on: ubuntu-latest
    needs: [job-1]
    env:
      VAR1 : "This is Job Level Variable-1"
      VAR2 : "This is Job Level Variable-2"
    steps:
    
      - name: Print env vars
        run : |
          echo "Var1 = ${{ env.VAR1 }}"
          echo "Var2 = ${{ env.VAR2 }}"
      - name: Print Name
        run: echo "My package name is :${{ env.MY_PACKAGE_NAME }}"
        
      - name: sleep
        run: sleep 3
